### ISSUE TITLE
How to download from Baidu link?

### ISSUE THREAD

**Issue by rst1991** [leofansq/CPCL#2]
@leofansq I am not able to access pre-trained weights from the Baidu link. Please guide regarding it. i am not able to create account on the Baidu portal as I dont have Chinese phone number.

**Comment by leofansq** [comment]
> @leofansq I am not able to access pre-trained weights from the Baidu link. Please guide regarding it. i am not able to create account on the Baidu portal as I dont have Chinese phone number.

We will upload some pretrained weights to GoogleDrive :)

**Comment by rst1991** [comment]
Please upload the dataset too on Google drive

**Comment by leofansq** [comment]
You can download the dataset from OneDrive following the guidance of CPS.
https://github.com/charlesCXK/TorchSemiSeg/blob/main/docs/getting_started.md#data-preparation

**Comment by rst1991** [comment]
Thanks, I'll check it out.

**Comment by leofansq** [comment]
@rst1991 We have uploaded several representative pretrained models (data partition = 1/8) to GoogleDrive, and the links in README is updated.

**Comment by gonelove31** [comment]
Just tried https://baidufast.com/ and it actually works pretty well. They give  for free. Honestly, that’s pretty cheap compared to most of these services.
