### ISSUE TITLE
Ignore index

### ISSUE THREAD

**Issue by rst1991** [leofansq/CPCL#3]
@leofansq Why ignore index=255 is used in the lost function? I have observed that there are 21 classes in prediction where groundtruth has values 0 to 20 and 255? Please explain this.

**Comment by leofansq** [comment]
There are 21 foreground semantic classes and one background class.

**Comment by rst1991** [comment]
Pascal Voc has 20 foreground classes and 1 background class. It is given on
paper too.

**Comment by rst1991** [comment]
According to the code 0 is background class, 1 to 20 is foreground class
and additional index of 255 is ignore index. Is this correct interpretation?

**Comment by leofansq** [comment]
Sorry for my misleading answer. 255 is the ignored label in Cityscapes. As for PascalVoc,  you can transfer 0 to 255, if you want to ignore background while training.
