### ISSUE TITLE
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by XieZhiyao21** [leofansq/CPCL#4]
When I am trying to reproduce this project,I encountered this problem.What can I do to solve this problem?Thanks in advance!

**Comment by leofansq** [comment]
It is caused by your CUDA environment. See https://stackoverflow.com/questions/55224016/importerror-libcublas-so-10-0-cannot-open-shared-object-file-no-such-file-or for more information.

**Comment by XieZhiyao21** [comment]
Thank you!I found the problem is that I erroneously configed the CUDA path.
