### ISSUE TITLE
Regarding dataset partitioning under the directory "DATA/pascal_voc/subset_train_aug".

### ISSUE THREAD

**Issue by XieZhiyao21** [leofansq/CPCL#5]
I would like to know how the files "pseudoseg_labeled_1-x.txt" and "pseudoseg_unlabeled_1-x.txt" in this directory are divided? How are they divided? 

Or in other words, why do the contents of these files (image names) originate from the directory "train_aug"? For example, why does "pseudoseg_labeled_1-2.txt" have 733 image names when 733 is not half the number of images (10,582) in the "train_aug" directory? Can you give me the code you used to divide the dataset, or explain it? Recently I would like to test your proposed CPCL method with other datasets. 

Thank you very much!

**Comment by leofansq** [comment]
Actually, they are for different experiment settings. The 'train_aug' is to evaluate the performance under full-supervision with additional data. 
We followed the partition protocols of the previous works for fair comparison. Please refer to the paper for more details.

**Comment by XieZhiyao21** [comment]
I see, in your paper about the CPCL method, the files "pseudoseg_labeled_1-x.txt" and "pseudoseg_unlabeled_1-x.txt" in the directory "DATA\pascal_voc\subset_train_aug" are just a selection of images based on a low amount of data, right?
Because the original image of VOC2012 dataset is exactly 1.4k, so it should be understandable, right?

Thank you for replying!
